---
  - hosts: all
    remote_user: vagrant
    become: true
    gather_facts: yes
    tasks: 
      - name: Print the remote machine hostname & IP
        debug:
          #msg: VM {{ ansible_nodename }} has {{ ansible_os_family }} OS and IP {{ ansible_all_ipv4_addresses }}
          msg: This machine has {{ ansible_os_family }} OS
