# Playbook using with_dict condition
---
  - hosts: dev
    gather_facts: no
    vars:
      package:
        apache: httpd
        shell: zsh
        ntp: ntpd
        python: python3
        mysql: mysql
    tasks:
      - name: Install packages
        yum:
         name: "{{ item.value }}"
         state: present
         with_dict: "{{ package }}"
         #loop: "{{ package }}"
   
   
   

