---
  - hosts: all
    gather_facts: no
    tasks:
        - name: Insert new line into a file
          lineinfile:
            path: /tmp/newfile
            line: ipaddress - ifconfig
            
          