# Generic
---
  - hosts: all
    remote_user: vagrant
    become: true
    gather_facts: no
    ignore_errors: true
    vars:
      - package: nginx
     #- service: httpd
    tasks:
     - name: Install "{{ package }}"
       yum:
        name: '{{ package }}' 
        state: present
       notify: restart "{{ package }}"
    handlers:
     - name: restart "{{ package }}"
       service:
         name: '{{ package }}'
         state: restarted

