---
  - hosts: all
    remote_user: vagrant
    become: true
    gather_facts: no
    ignore_errors: yes
    become: true
    tasks: 
      - name: Install apache
        apt: name=apache2 state=present
        tags: http
      - name: Install ntp
        yum: name=ntpd state=present
        tags: ntp
      - name: Install PHP
        yum: name=php5 state=present
        tags: php

