apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: scale-out-pod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache-deploy
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
